title: "Node Tap"
description: A Test-Anything-Protocol library for Node.js
links:
  - name: "Index"
    url: "/"
  - name: "Getting Started"
    url: "/basics/"
  - name: "API"
    url: "/api/"
    links:
    - name: "Asserts"
      url: "/asserts/"
    - name: "Promises"
      url: "/promises/"
    - name: "Advanced"
      url: "/advanced/"
  - name: "CLI"
    url: "/cli/"
  - name: "Reporting"
    url: "/reporting/"
  - name: "Coverage"
    url: "/coverage/"
  - name: "Change Log"
    url: "/changelog/"
  - name: "GitHub Repo"
    url: "https://github.com/tapjs/node-tap"

# Build settings
markdown: kramdown
markdown_ext:  md

kramdown:
  input: GFM
  syntax_highlighter: rouge
